name: Update gist with WakaTime stats
on:
  push:
    branches: 
      - main 
  schedule:
    - cron: "0 5 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update gist
        uses: danydodson/waka-box@main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
